name: Schedule Reminder

on:
  schedule:
    - cron: '*/10 * * * *'  # Her 10 dakikada bir

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Çağrı: /api/reminder
        run: |
          curl -s -X GET https://whatsapp-saas.vercel.app/
